import {
    AboutHeaderBlock,
    AdvantagesBlock,
    AudioBlock,
    BannerBlock,
    BannerMinifyBlock,
    BenchmarkBlock,
    BenefitsBlock,
    BlogFeedBlock,
    CardLayoutBlock,
    CatBlock,
    CompaniesBlock,
    ContentLayoutBlock,
    CustomerStoriesFeedBlock,
    EventsFeedBlock,
    EventsSectionBlock,
    ExtendedFeaturesBlock,
    FilterBlock,
    FilterCardLayoutBlock,
    FormBlock,
    FormWallBlock,
    HeaderBlock,
    HeaderMinifyBlock,
    HeaderSliderBlock,
    HighlightTableBlock,
    IconsBlock,
    InfoBlock,
    LayoutBlock,
    LinkTableBlock,
    LogoRotatorBlock,
    MapBlock,
    MarqueeLinksBlock,
    MediaBlock,
    MiniCaseBlock,
    OnetrustCookieListBlock,
    PartnerHeaderBlock,
    PartnersFeedBlock,
    PressReleasesBlock,
    PromoFeaturesBlock,
    QuestionsBlock,
    QuotesBlock,
    RelevantPostsBlock,
    RelevantReportsBlock,
    RelevantReportsCardsBlock,
    ReportsBlock,
    ReportsCardsBlock,
    ReportsSectionsBlock,
    ResourceHubPostsBlock,
    ScienceFeedBlock,
    ScienceHeaderBlock,
    ScienceSuggestBlock,
    ScrollerBlock,
    ServicesBlock,
    ShareBlock,
    SidebarWidgetBlock,
    SliderBlock,
    SliderNewBlock,
    SolutionsBlock,
    TabLinksBlock,
    TableBlock,
    TabsBlock,
    TabsHighlightTableBlock,
    UnicornCardsBlock,
    WhatsNewBlock,
    YFMBlock,
} from './blocks';
import {BlockType, NavigationItemType, SubBlockType} from './models';
import {
    GithubButton,
    NavigationButton,
    NavigationDropdown,
    NavigationLink,
} from './navigation/components/NavigationItem';
import SocialIcon from './navigation/components/SocialIcon/SocialIcon';
import {
    AttachmentCard,
    BackgroundCard,
    BannerCard,
    BasicCard,
    Card,
    CaseStudyCard,
    Content,
    ContentLayoutCard,
    Divider,
    EventPersonCard,
    FeedCard,
    FeedPartner,
    ImageCard,
    LayoutItem,
    MediaCard,
    NewPostCard,
    NewsCard,
    PostCard,
    PriceCard,
    PriceDetailed,
    Quote,
    StoryCard,
    MiniCaseCard,
} from './sub-blocks';

export const blockMap = {
    [BlockType.SliderBlock]: SliderBlock,
    [BlockType.ExtendedFeaturesBlock]: ExtendedFeaturesBlock,
    [BlockType.PromoFeaturesBlock]: PromoFeaturesBlock,
    [BlockType.AdvantagesBlock]: AdvantagesBlock,
    [BlockType.BenefitsBlock]: BenefitsBlock,
    [BlockType.ScrollerBlock]: ScrollerBlock,
    [BlockType.QuestionsBlock]: QuestionsBlock,
    [BlockType.BannerBlock]: BannerBlock,
    [BlockType.LogoRotatorBlock]: LogoRotatorBlock,
    [BlockType.UnicornCardsBlock]: UnicornCardsBlock,
    [BlockType.CompaniesBlock]: CompaniesBlock,
    [BlockType.MediaBlock]: MediaBlock,
    [BlockType.InfoBlock]: InfoBlock,
    [BlockType.TableBlock]: TableBlock,
    [BlockType.TabsBlock]: TabsBlock,
    [BlockType.TabsHighlightTableBlock]: TabsHighlightTableBlock,
    [BlockType.TabLinksBlock]: TabLinksBlock,
    [BlockType.HeaderBlock]: HeaderBlock,
    [BlockType.HeaderMinifyBlock]: HeaderMinifyBlock,
    [BlockType.IconsBlock]: IconsBlock,
    [BlockType.HeaderSliderBlock]: HeaderSliderBlock,
    [BlockType.CardLayoutBlock]: CardLayoutBlock,
    [BlockType.ContentLayoutBlock]: ContentLayoutBlock,
    [BlockType.BannerMinifyBlock]: BannerMinifyBlock,
    [BlockType.ShareBlock]: ShareBlock,
    [BlockType.MapBlock]: MapBlock,
    [BlockType.FilterBlock]: FilterBlock,
    [BlockType.FilterCardLayoutBlock]: FilterCardLayoutBlock,
    [BlockType.FormBlock]: FormBlock,
    [BlockType.MarqueeLinksBlock]: MarqueeLinksBlock,
    [BlockType.SolutionsBlock]: SolutionsBlock,
    [BlockType.EventsFeedBlock]: EventsFeedBlock,
    [BlockType.PartnersFeedBlock]: PartnersFeedBlock,
    [BlockType.ResourceHubPostsBlock]: ResourceHubPostsBlock,
    [BlockType.BenchmarkBlock]: BenchmarkBlock,
    [BlockType.EventsSectionBlock]: EventsSectionBlock,
    [BlockType.BlogFeedBlock]: BlogFeedBlock,
    [BlockType.ScienceFeedBlock]: ScienceFeedBlock,
    [BlockType.CustomerStoriesFeedBlock]: CustomerStoriesFeedBlock,
    [BlockType.RelevantPostsBlock]: RelevantPostsBlock,
    [BlockType.RelevantReportsCardsBlock]: RelevantReportsCardsBlock,
    [BlockType.RelevantReportsBlock]: RelevantReportsBlock,
    [BlockType.PressReleasesBlock]: PressReleasesBlock,
    [BlockType.HighlightTableBlock]: HighlightTableBlock,
    [BlockType.MiniCaseBlock]: MiniCaseBlock,
    [BlockType.LinkTableBlock]: LinkTableBlock,
    [BlockType.ServicesBlock]: ServicesBlock,
    [BlockType.QuotesBlock]: QuotesBlock,
    [BlockType.ReportsBlock]: ReportsBlock,
    [BlockType.ScienceHeaderBlock]: ScienceHeaderBlock,
    [BlockType.ScienceSuggestBlock]: ScienceSuggestBlock,
    [BlockType.AboutHeaderBlock]: AboutHeaderBlock,
    [BlockType.LayoutBlock]: LayoutBlock,
    [BlockType.YFMBlock]: YFMBlock,
    [BlockType.PartnerHeaderBlock]: PartnerHeaderBlock,
    [BlockType.SidebarWidgetBlock]: SidebarWidgetBlock,
    [BlockType.ReportsCardsBlock]: ReportsCardsBlock,
    [BlockType.ReportsSectionsBlock]: ReportsSectionsBlock,
    [BlockType.FormWallBlock]: FormWallBlock,
    [BlockType.SliderNewBlock]: SliderNewBlock,
    [BlockType.CatBlock]: CatBlock,
    [BlockType.AudioBlock]: AudioBlock,
    [BlockType.OnetrustCookieListBlock]: OnetrustCookieListBlock,
    [BlockType.WhatsNewBlock]: WhatsNewBlock,
};

export const subBlockMap = {
    [SubBlockType.Divider]: Divider,
    [SubBlockType.PriceDetailed]: PriceDetailed,
    [SubBlockType.MediaCard]: MediaCard,
    [SubBlockType.BannerCard]: BannerCard,
    [SubBlockType.LayoutItem]: LayoutItem,
    [SubBlockType.NewsCard]: NewsCard,
    [SubBlockType.BackgroundCard]: BackgroundCard,
    [SubBlockType.BasicCard]: BasicCard,
    [SubBlockType.Content]: Content,
    [SubBlockType.Quote]: Quote,
    [SubBlockType.PriceCard]: PriceCard,
    [SubBlockType.ImageCard]: ImageCard,
    [SubBlockType.ContentLayoutCard]: ContentLayoutCard,
    [SubBlockType.Card]: Card,
    [SubBlockType.PostCard]: PostCard,
    [SubBlockType.NewPostCard]: NewPostCard,
    [SubBlockType.FeedCard]: FeedCard,
    [SubBlockType.EventPersonCard]: EventPersonCard,
    [SubBlockType.AttachmentCard]: AttachmentCard,
    [SubBlockType.FeedPartner]: FeedPartner,
    [SubBlockType.CaseStudyCard]: CaseStudyCard,
    [SubBlockType.StoryCard]: StoryCard,
    [SubBlockType.MiniCaseCard]: MiniCaseCard,
};

export const navItemMap = {
    [NavigationItemType.Button]: NavigationButton,
    [NavigationItemType.Social]: SocialIcon,
    [NavigationItemType.Dropdown]: NavigationDropdown,
    [NavigationItemType.Link]: NavigationLink,
    [NavigationItemType.GithubButton]: GithubButton,
};
