import {
    AdvantagesBlock,
    BannerBlock,
    BannerMinifyBlock,
    BenchmarkBlock,
    BlogFeedBlock,
    CardLayoutBlock,
    CompaniesBlock,
    ContentLayoutBlock,
    EventsFeedBlock,
    EventsSectionBlock,
    ExtendedFeaturesBlock,
    FilterBlock,
    FilterCardLayoutBlock,
    FormBlock,
    FormWallBlock,
    HeaderBlock,
    HeaderMinifyBlock,
    HeaderSliderBlock,
    HighlightTableBlock,
    IconsBlock,
    InfoBlock,
    LinkTableBlock,
    LogoRotatorBlock,
    MapBlock,
    MarqueeLinksBlock,
    MediaBlock,
    MiniCaseBlock,
    PressReleasesBlock,
    PromoFeaturesBlock,
    QuestionsBlock,
    QuotesBlock,
    RelevantPostsBlock,
    RelevantReportsBlock,
    RelevantReportsCardsBlock,
    ReportsBlock,
    ReportsCardsBlock,
    ReportsSectionsBlock,
    ServicesBlock,
    ShareBlock,
    SliderBlock,
    SliderNewBlock,
    SolutionsBlock,
    TabLinksBlock,
    TableBlock,
    TabsBlock,
    TabsHighlightTableBlock,
} from './blocks';
import {BlockType, NavigationItemType, SubBlockType} from './models';
import {
    GithubButton,
    NavigationButton,
    NavigationDropdown,
    NavigationLink,
} from './navigation/components/NavigationItem';
import SocialIcon from './navigation/components/SocialIcon/SocialIcon';
import {
    AttachmentCard,
    BackgroundCard,
    BannerCard,
    BasicCard,
    Card,
    CaseStudyCard,
    Content,
    ContentLayoutCard,
    Divider,
    EventPersonCard,
    FeedCard,
    ImageCard,
    LayoutItem,
    MediaCard,
    PostCard,
    PriceCard,
    PriceDetailed,
    Quote,
    StoryCard,
} from './sub-blocks';

export const blockMap = {
    [BlockType.SliderBlock]: SliderBlock,
    [BlockType.ExtendedFeaturesBlock]: ExtendedFeaturesBlock,
    [BlockType.PromoFeaturesBlock]: PromoFeaturesBlock,
    [BlockType.AdvantagesBlock]: AdvantagesBlock,
    [BlockType.QuestionsBlock]: QuestionsBlock,
    [BlockType.BannerBlock]: BannerBlock,
    [BlockType.LogoRotatorBlock]: LogoRotatorBlock,
    [BlockType.CompaniesBlock]: CompaniesBlock,
    [BlockType.MediaBlock]: MediaBlock,
    [BlockType.InfoBlock]: InfoBlock,
    [BlockType.TableBlock]: TableBlock,
    [BlockType.TabsBlock]: TabsBlock,
    [BlockType.TabsHighlightTableBlock]: TabsHighlightTableBlock,
    [BlockType.TabLinksBlock]: TabLinksBlock,
    [BlockType.HeaderBlock]: HeaderBlock,
    [BlockType.HeaderMinifyBlock]: HeaderMinifyBlock,
    [BlockType.IconsBlock]: IconsBlock,
    [BlockType.HeaderSliderBlock]: HeaderSliderBlock,
    [BlockType.CardLayoutBlock]: CardLayoutBlock,
    [BlockType.ContentLayoutBlock]: ContentLayoutBlock,
    [BlockType.BannerMinifyBlock]: BannerMinifyBlock,
    [BlockType.ShareBlock]: ShareBlock,
    [BlockType.MapBlock]: MapBlock,
    [BlockType.FilterBlock]: FilterBlock,
    [BlockType.FilterCardLayoutBlock]: FilterCardLayoutBlock,
    [BlockType.FormBlock]: FormBlock,
    [BlockType.MarqueeLinksBlock]: MarqueeLinksBlock,
    [BlockType.SolutionsBlock]: SolutionsBlock,
    [BlockType.EventsFeedBlock]: EventsFeedBlock,
    [BlockType.BenchmarkBlock]: BenchmarkBlock,
    [BlockType.EventsSectionBlock]: EventsSectionBlock,
    [BlockType.BlogFeedBlock]: BlogFeedBlock,
    [BlockType.RelevantPostsBlock]: RelevantPostsBlock,
    [BlockType.RelevantReportsCardsBlock]: RelevantReportsCardsBlock,
    [BlockType.RelevantReportsBlock]: RelevantReportsBlock,
    [BlockType.PressReleasesBlock]: PressReleasesBlock,
    [BlockType.HighlightTableBlock]: HighlightTableBlock,
    [BlockType.MiniCaseBlock]: MiniCaseBlock,
    [BlockType.LinkTableBlock]: LinkTableBlock,
    [BlockType.ServicesBlock]: ServicesBlock,
    [BlockType.QuotesBlock]: QuotesBlock,
    [BlockType.ReportsBlock]: ReportsBlock,
    [BlockType.ReportsCardsBlock]: ReportsCardsBlock,
    [BlockType.ReportsSectionsBlock]: ReportsSectionsBlock,
    [BlockType.FormWallBlock]: FormWallBlock,
    [BlockType.SliderNewBlock]: SliderNewBlock,
};

export const subBlockMap = {
    [SubBlockType.Divider]: Divider,
    [SubBlockType.PriceDetailed]: PriceDetailed,
    [SubBlockType.MediaCard]: MediaCard,
    [SubBlockType.BannerCard]: BannerCard,
    [SubBlockType.LayoutItem]: LayoutItem,
    [SubBlockType.BackgroundCard]: BackgroundCard,
    [SubBlockType.BasicCard]: BasicCard,
    [SubBlockType.Content]: Content,
    [SubBlockType.Quote]: Quote,
    [SubBlockType.PriceCard]: PriceCard,
    [SubBlockType.ImageCard]: ImageCard,
    [SubBlockType.ContentLayoutCard]: ContentLayoutCard,
    [SubBlockType.Card]: Card,
    [SubBlockType.PostCard]: PostCard,
    [SubBlockType.FeedCard]: FeedCard,
    [SubBlockType.EventPersonCard]: EventPersonCard,
    [SubBlockType.AttachmentCard]: AttachmentCard,
    [SubBlockType.CaseStudyCard]: CaseStudyCard,
    [SubBlockType.StoryCard]: StoryCard,
};

export const navItemMap = {
    [NavigationItemType.Button]: NavigationButton,
    [NavigationItemType.Social]: SocialIcon,
    [NavigationItemType.Dropdown]: NavigationDropdown,
    [NavigationItemType.Link]: NavigationLink,
    [NavigationItemType.GithubButton]: GithubButton,
};
