import {
    BannerBlock,
    BlogFeedBlock,
    CardLayoutBlock,
    CompaniesBlock,
    ContentLayoutBlock,
    EventsFeedBlock,
    ExtendedFeaturesBlock,
    FilterBlock,
    FormBlock,
    FormWallBlock,
    HeaderBlock,
    HeaderSliderBlock,
    HighlightTableBlock,
    IconsBlock,
    InfoBlock,
    LinkTableBlock,
    MapBlock,
    MarqueeLinksBlock,
    MediaBlock,
    PressReleasesBlock,
    PromoFeaturesBlock,
    QuestionsBlock,
    QuotesBlock,
    RelevantPostsBlock,
    ReportsBlock,
    ReportsSectionsBlock,
    ServicesBlock,
    ShareBlock,
    SliderBlock,
    SolutionsBlock,
    TableBlock,
    TabsBlock,
} from './blocks';
import {SliderNewBlock} from './blocks/unstable';
import {BlockType, NavigationItemType, SubBlockType} from './models';
import {
    GithubButton,
    NavigationButton,
    NavigationDropdown,
    NavigationLink,
} from './navigation/components/NavigationItem';
import SocialIcon from './navigation/components/SocialIcon/SocialIcon';
import {
    AttachmentCard,
    BackgroundCard,
    BannerCard,
    BasicCard,
    Card,
    CaseStudyCard,
    Content,
    ContentLayoutCard,
    Divider,
    EventPersonCard,
    FeedCard,
    ImageCard,
    LayoutItem,
    MediaCard,
    PostCard,
    PriceCard,
    PriceDetailed,
    Quote,
} from './sub-blocks';

export const blockMap = {
    [BlockType.SliderBlock]: SliderBlock,
    [BlockType.ExtendedFeaturesBlock]: ExtendedFeaturesBlock,
    [BlockType.PromoFeaturesBlock]: PromoFeaturesBlock,
    [BlockType.QuestionsBlock]: QuestionsBlock,
    [BlockType.BannerBlock]: BannerBlock,
    [BlockType.CompaniesBlock]: CompaniesBlock,
    [BlockType.MediaBlock]: MediaBlock,
    [BlockType.InfoBlock]: InfoBlock,
    [BlockType.TableBlock]: TableBlock,
    [BlockType.TabsBlock]: TabsBlock,
    [BlockType.HeaderBlock]: HeaderBlock,
    [BlockType.IconsBlock]: IconsBlock,
    [BlockType.HeaderSliderBlock]: HeaderSliderBlock,
    [BlockType.CardLayoutBlock]: CardLayoutBlock,
    [BlockType.ContentLayoutBlock]: ContentLayoutBlock,
    [BlockType.ShareBlock]: ShareBlock,
    [BlockType.MapBlock]: MapBlock,
    [BlockType.FilterBlock]: FilterBlock,
    [BlockType.FormBlock]: FormBlock,
    [BlockType.MarqueeLinksBlock]: MarqueeLinksBlock,
    [BlockType.SolutionsBlock]: SolutionsBlock,
    [BlockType.EventsFeedBlock]: EventsFeedBlock,
    [BlockType.BlogFeedBlock]: BlogFeedBlock,
    [BlockType.RelevantPostsBlock]: RelevantPostsBlock,
    [BlockType.PressReleasesBlock]: PressReleasesBlock,
    [BlockType.HighlightTableBlock]: HighlightTableBlock,

    [BlockType.LinkTableBlock]: LinkTableBlock,
    [BlockType.ServicesBlock]: ServicesBlock,
    [BlockType.QuotesBlock]: QuotesBlock,
    [BlockType.ReportsBlock]: ReportsBlock,
    [BlockType.ReportsSectionsBlock]: ReportsSectionsBlock,
    [BlockType.FormWallBlock]: FormWallBlock,
    // unstable
    [BlockType.SliderNewBlock]: SliderNewBlock,
};

export const subBlockMap = {
    [SubBlockType.Divider]: Divider,
    [SubBlockType.PriceDetailed]: PriceDetailed,
    [SubBlockType.MediaCard]: MediaCard,
    [SubBlockType.BannerCard]: BannerCard,
    [SubBlockType.LayoutItem]: LayoutItem,
    [SubBlockType.BackgroundCard]: BackgroundCard,
    [SubBlockType.BasicCard]: BasicCard,
    [SubBlockType.Content]: Content,
    [SubBlockType.Quote]: Quote,
    [SubBlockType.PriceCard]: PriceCard,
    [SubBlockType.ImageCard]: ImageCard,
    [SubBlockType.ContentLayoutCard]: ContentLayoutCard,
    [SubBlockType.Card]: Card,
    [SubBlockType.PostCard]: PostCard,
    [SubBlockType.FeedCard]: FeedCard,
    [SubBlockType.EventPersonCard]: EventPersonCard,
    [SubBlockType.AttachmentCard]: AttachmentCard,
    [SubBlockType.CaseStudyCard]: CaseStudyCard,
};

export const navItemMap = {
    [NavigationItemType.Button]: NavigationButton,
    [NavigationItemType.Social]: SocialIcon,
    [NavigationItemType.Dropdown]: NavigationDropdown,
    [NavigationItemType.Link]: NavigationLink,
    [NavigationItemType.GithubButton]: GithubButton,
};
